[project]
name = "vosk-imp"
version = "0.1.0"
description = ""
authors = [
	{ name = "Cammy", email = "cameronsteele@steelecameron.com" }
]
readme = "README.md"
dependencies = [
	"python >=3.10,<4",
	"sounddevice >=0.4.6",
	"vosk >=0.3.45"
]
