[project]
name = "vosk-imp"
version = "0.1.0"
description = ""
authors = [
	{ name = "Cammy", email = "cameronsteele@steelecameron.com" }
]
readme = "README.md"
requires-python = ">=3.9.0,<3.11"
dependencies = [
	"sounddevice >=0.4.6",
	"vosk >=0.3.45"
]
